name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
          sudo apt install libboost-all-dev
    - uses: actions/checkout@v1
    - name: build dir
      run: mkdir build  
    - name: make test_array
      run: make test_array
    - name: make test_processor
      run: make test_processor
    - name: make test_parser
      run: make test_parser
    - name: make test_speed
      run: make test_speed
