name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install dependencies
      run: |
          sudo apt install libboost-all-dev
    - uses: actions/checkout@v1
    - name: make test_expr
      run: make test_expr
    - name: make test_processor
      run: make test_processor
    - name: make test_parser
      run: make test_parser
